require("wienio.plugins")
require("wienio.setup.autopair")
<<<<<<< HEAD
require("wienio.setup.nvimtree")
=======
>>>>>>> 75f9b0b24d3048a1dc2d7ec50c19d6f60802bad9
require("wienio.setup.lspsaga")
require("wienio.setup.null-ls")
require("wienio.setup.toggleterm")
require("wienio.setup.dressing")
require("wienio.setup.mason")
require("wienio.setup.nvimcmp")
require("wienio.setup.telescope")
require("wienio.setup.treesitter")
require("wienio.setup.lspconfig")
require("wienio.setup.lualine")
require("wienio.setup.barbar")
require("wienio.setup.undotree")
require("wienio.cfg.keymap")
require("wienio.cfg.options")
vim.cmd("colorscheme default")
