require("wienio.plugins")
require("wienio.setup.autopair")
require("wienio.setup.lspsaga")
require("wienio.setup.null-ls")
require("wienio.setup.nvimtree")
require("wienio.setup.toggleterm")
require("wienio.setup.dressing")
require("wienio.setup.mason")
require("wienio.setup.nvimcmp")
require("wienio.setup.telescope")
require("wienio.setup.treesitter")
require("wienio.setup.lspconfig")
require("wienio.cfg.keymap")
require("wienio.cfg.options")
vim.cmd("colorscheme PaperColor")
